baseurl: ""
url: ""

# Email to be used by the contact button
email: fcaboyo@gmail.com

# Name of website owner
name: Francis Anthony Carmel

# Profession or qualification
designation: Designer Developer

# Personal choice of quote
tagline: Loving what you do, doing what you love

# Contact button text
contact_label: Get in touch

# Default website title
title: Franthormel

note_article: This serves as a rundown of the book and does not serve in any way to be a complete replacement. It is highly advised to read the book itself.

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
