baseurl: ""
url: ""

email: fcaboyo@gmail.com
name: Francis Anthony Carmel

designation: Designer Developer
tagline: Loving what you do, doing what you love
contact_label: Get in touch
title: Franthormel
description: This is the personal website of Francis Anthony Carmel.
author: Francis Anthony Carmel

article_footer: This serves as a pocket guide and not a complete replacement. It is highly advised to read the actual material.

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
